### ISSUE TITLE
Thoughts on potential improvements

### ISSUE THREAD

**Issue by S0fian3M** [rubingshen/AugmentedSocialScientist#2]
Hello, Firstly, great work on this project! I am interested in the use of this library for computational social sciences, and I would love to contribute and collaborate with the development. I have some ideas for potential improvements, although before I proceed, I wanted to inquire if you are open to accepting pull requests for the project. E.g. : reduce auxiliary dependencies (are tensorflow and pandas necessary?), I suggest creating a general interface class as many of the classes in the project seem to share similar functionalities.
Please let me know your thoughts on these suggestions and whether you are open to accepting contributions. If so, I'll be glad to get started on the proposed changes!

**Comment by rubingshen** [comment]
Hi! You're very welcome to contribute and send pull requests and I agree with the potential improvements suggested by you. Thank you in advance!

**Comment by S0fian3M** [comment]
Great, thanks! I made a pull request :)
